/* SQL */

/* SELECT ALL COLUMNS FROM TABLE */
SELECT *
FROM TABLE

/* SELECT SOME FIELDS FROM TABLE */
SELECT T.A, 
       T.B,
       T.C
FROM TABLE AS T

/* SELECT DISTINCT VALUES */
SELECT 
    DISTINCT(T.A)
FROM TABLE AS T

/* COUNT AN AVG FUNCTIONS*/
SELECT T.A AS NAME,
       AVG(T.B) AS AVERAGE,
       COUNT(T.C) AS COUNT_VALUES
FROM TABLE AS T
GROUP BY T.A /* OR ALIAS */

/* MATH OPERATIONS */
SELECT SUM(T.A) AS VALUES_SUM,
       SUM(T.A + T.B) AS SUM_FIELDS,
       SUM(T.A - T.B) AS SUBTRACTION,
       (T.A * T.B) AS MULTIPLICATION,
       (T.A / T.B) AS DIVISION
       POWER(T.A) AS EXPONENTIATION_1
       ABS(T.B) AS ABSOLUTE_VALUE
       MIN(T.A) AS MININUM_VALUE,
       MAX(T.A) AS MAX_VALUE
FROM TABLE AS T
GROUP BY 1,2,3,4,5,6,7,8,9

/* ROUND AND COALESCE(Return non null values)*/
SELECT ROUND(T.A, 2) AS ROUNDED_VALUES,
       TRUNCATE(T.A, 2) AS TRUNC_ROUNDED_VALUES,
       COALESCE(T.B) AS NOT_NULL
FROM TABLE AS T

/* CAST, SUBSTR(MID OR SUBSTRING), CONCAT */
SELECT SUBSTR(T.A, 5, 3), /* EXTRACT 3 CHARS STARTING ON POSITION 5 */
       CAST(T.B AS NCHAR),
       CONCAT(T.C, T.D) AS CONCATENATED_COLUMNS,
       CONCAT_WS("-", T.C, T.D), /* CONCAT WITH - BETWEEN THE WORDS */
       TRIM(T.C) /* REMOVE LEADING AND TRAILING SPACES */
FROM TABLE AS T

/* GROUP BY AND ORDER BY */
SELECT T.A,
       T.B AS FIELD
FROM TABLE AS T
GROUP BY T.A, FIELD
ORDER BY T.A ASC  /* OR DESC */

/* LIMIT */
SELECT * 
FROM TABLE AS T
LIMIT 10




